name: Deploy Flask App to VM

on:
  push:
    branches:
      - main
    paths:
      newfile.txt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project to VM
        uses: appleboy/scp-action@v0.1.7
        with:
           host: ${{ vars.VM_HOST }}
           username: ${{ vars.VM_USER }}
           key: ${{ secrets.SSHPRIVATEKEY }}
           source: "."
           target: "/var/www/flaskapp"

      - name: SSH into VM and set up app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.SSHPRIVATEKEY }}
          script: |
            cd /var/www/flaskapp
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp
